services:
  aspnet-app:
    container_name: aspnet-app
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: CybersecurityProject/Dockerfile
    image: cybersecurityproject-aspnet-app
    
  
  nginx:
    container_name: nginx
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    image: cybersecurityproject-nginx
    
